#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
    
fos_oauth_server_token:
        resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: AppBundle:Security:login }

oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: AppBundle:Security:loginCheck }

logout:
    pattern:  /logout
    defaults: { _controller: AppBundle:Security:logout }   
   
restapi:
    type: rest
    prefix: /api
    resource: "@AppBundle/Resources/config/api_routes.yml"

app:
    resource: "@AppBundle/Resources/config/routes.yml"
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /docapi